### ISSUE TITLE
Home Page To-Do

### ISSUE THREAD

**Issue by MichaelTamaki** [BerkeleyBlockchain/the-website#1]
Create and style components of the home page to put together! Comment which component you are working on.
- [ ] Jumbotron
- [ ] What do we do?
- [ ] Join our Mailing List
- [ ] Contact Us
- [ ] Get Involved (footer)

**Comment by MichaelTamaki** [comment]
I'm going to work on the Jumbotron, hopefully will have finished by Sunday.

**Comment by ntalcus** [comment]
I'll work on the contact us stuff.

**Comment by MichaelTamaki** [comment]
The components are done now. More work needs to be done on the responsive design (waiting on mobile design docs) and figuring out how the mailing list works.
